#!/usr/bin/env python
#coding=utf-8

# radius = 25 
# Input(輸入):Prompt the user to enter a radius
radius = eval(input("Enter a number for radius: "))

# Processing(處理):Compute area
area = radius * radius * 3.1415962

# Output(輸出):Display results
print("The area for the circle of radius", radius, "is", area)


#!/usr/bin/env python
#coding=utf-8

# Prompt the user to enter three numbers
number1, number2, number3 = eval(input("Enter three numbers separated by commas: "))

# Compute average
average = (number1 + number2 + number3) / 3

# Display result
print("The average of", number1, number2, number3, "is", average)


>>> q = 259
>>> p = 0.038
>>> print(q, p, p * q)
>>> print(q, p, p * q, sep=",")
>>> print(q, p, p * q, sep=" :-) ")
>>> print(str(q) + " " + str(p) + " " + str(p * q))
